package sistemanenka_presentacion;

import com.sun.glass.events.KeyEvent;
import control.INegocios;
import dominio.Categoria;
import dominio.Cliente;
import dominio.DetalleVenta;
import dominio.Empleado;
import dominio.Producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import models.JTableButtonRenderer;
import models.PreviaProductoRenderer;

/**
 *
 * @author dianacastro
 */
public class FmAdministrarProductos extends FmBase {

    DefaultTableModel modeloTabla;
    INegocios negocios;
    Empleado empleado;

    /**
     * Creates new form FmRealizarVenta
     */
    public FmAdministrarProductos(Empleado empleado) {
        initComponents();
        this.empleado = empleado;
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        cbCategorias = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAñadirProducto = new javax.swing.JButton();
        pnlPrevia = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPrevia = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAdministrador = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1115, 650));
        setSize(new java.awt.Dimension(1115, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCategoria.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCategoria.setText("Categoria:");
        jPanel1.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 100, 20));

        cbCategorias.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategorias.setBorder(null);
        cbCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCategoriasMouseClicked(evt);
            }
        });
        cbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriasActionPerformed(evt);
            }
        });
        jPanel1.add(cbCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 210, 40));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 50, 30));

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 118, 176)));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 250, 40));

        btnCancelar.setBackground(new java.awt.Color(243, 69, 51));
        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 130, 40));

        btnAñadirProducto.setBackground(new java.awt.Color(118, 194, 124));
        btnAñadirProducto.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnAñadirProducto.setText("AÑADIR PRODUCTO");
        btnAñadirProducto.setBorder(null);
        btnAñadirProducto.setBorderPainted(false);
        btnAñadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 170, 40));

        lstPrevia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lstPrevia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPrevia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPreviaMouseClicked(evt);
            }
        });
        lstPrevia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstPreviaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(lstPrevia);

        javax.swing.GroupLayout pnlPreviaLayout = new javax.swing.GroupLayout(pnlPrevia);
        pnlPrevia.setLayout(pnlPreviaLayout);
        pnlPreviaLayout.setHorizontalGroup(
            pnlPreviaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pnlPreviaLayout.setVerticalGroup(
            pnlPreviaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPreviaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlPrevia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 250, 60));

        tbProductos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "PRECIO", "STOCK", "EDITAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProductosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbProductos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 760, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 870, 510));

        jPanel3.setBackground(new java.awt.Color(47, 118, 176));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdministrador.setBackground(new java.awt.Color(47, 118, 176));
        btnAdministrador.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/administracion.png"))); // NOI18N
        btnAdministrador.setText("Administrador");
        btnAdministrador.setBorder(null);
        btnAdministrador.setBorderPainted(false);
        btnAdministrador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdministrador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 140, 90));

        btnVenta.setBackground(new java.awt.Color(47, 118, 176));
        btnVenta.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cesta-de-la-compra.png"))); // NOI18N
        btnVenta.setText("Venta");
        btnVenta.setToolTipText("");
        btnVenta.setBorder(null);
        btnVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVenta.setMaximumSize(new java.awt.Dimension(134, 101));
        btnVenta.setMinimumSize(new java.awt.Dimension(134, 101));
        btnVenta.setPreferredSize(new java.awt.Dimension(134, 101));
        btnVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, 90));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Productos");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 250, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 720, 110));

        jPanel4.setBackground(new java.awt.Color(47, 111, 159));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("SISTEMA NENKA");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministradorActionPerformed

    private void btnAñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirProductoActionPerformed
        FrAgregarProducto fProductos = new FrAgregarProducto(empleado, null);
        fProductos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAñadirProductoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FmRealizarVenta realizarVenta = new FmRealizarVenta(empleado);
        realizarVenta.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        buscarProductos();
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void buscarProductos() {
        List<Producto> productos = negocios.buscarProducto(txtBuscar.getText());
        List<Producto> productos1 = negocios.buscarProductoCategoria(txtBuscar.getText());
        if (productos.isEmpty() && productos1.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "No se encontró ningún producto en esta búsqueda.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!productos1.isEmpty()) {
            crearListaPreviaProductos(productos1);
        } else {
            crearListaPreviaProductos(productos);
        }
    }

    private void lstPreviaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPreviaMouseClicked
        int i = lstPrevia.getSelectedIndex();
        Producto producto = lstPrevia.getModel().getElementAt(i);
        agregaProductoBuscado(producto);
    }//GEN-LAST:event_lstPreviaMouseClicked

    private void lstPreviaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstPreviaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int i = lstPrevia.getSelectedIndex();
            Producto producto = lstPrevia.getModel().getElementAt(i);
            agregaProductoBuscado(producto);
        }
    }//GEN-LAST:event_lstPreviaKeyReleased

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased

    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void tbProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductosMouseClicked
        int column = tbProductos.getSelectedColumn();

        if (column == 4) {
            int row = tbProductos.getSelectedRow();

            int codigo = (int) tbProductos.getValueAt(row, 0);
            modificarProducto(codigo);
        }
    }//GEN-LAST:event_tbProductosMouseClicked

    private void cbCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCategoriasMouseClicked
//        Categoria c = (Categoria)cbCategorias.getSelectedItem();
//        List<Producto> productos = negocios.buscarProductoCategoria(c.getNombre());
//        modeloTabla.setRowCount(0);
//        for (Producto producto : productos) {
//            JButton btnEditar = new JButton();
//            btnEditar.setText("EDITAR");
//            Object[] fila = new Object[5];
//            fila[0] = producto.getCodigo();
//            fila[1] = producto.getNombre();
//            fila[2] = producto.getPrecio();
//            fila[3] = producto.getStock();
//            fila[4] = btnEditar;
//            modeloTabla.addRow(fila);
//        }
    }//GEN-LAST:event_cbCategoriasMouseClicked

    private void cbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriasActionPerformed
        Categoria c = (Categoria)cbCategorias.getSelectedItem();
        List<Producto> productos = negocios.buscarProductoCategoria(c.getNombre());
        modeloTabla.setRowCount(0);
        for (Producto producto : productos) {
            JButton btnEditar = new JButton();
            btnEditar.setText("EDITAR");
            Object[] fila = new Object[5];
            fila[0] = producto.getCodigo();
            fila[1] = producto.getNombre();
            fila[2] = producto.getPrecio();
            fila[3] = producto.getStock();
            fila[4] = btnEditar;
            modeloTabla.addRow(fila);
        }
    }//GEN-LAST:event_cbCategoriasActionPerformed

    private void modificarProducto(int codigo) {
        List<Producto> productos = negocios.obtenerProductos();
        for (Producto producto : productos) {
            if (producto.getCodigo() == codigo) {
                FrAgregarProducto fProductos = new FrAgregarProducto(empleado, producto);
                fProductos.setVisible(true);
                dispose();
            }
        }
    }

    private void agregaProductoBuscado(Producto producto) {
        modeloTabla.setRowCount(0);
        txtBuscar.setText("");
        pnlPrevia.setVisible(false);
        JButton btnEditar = new JButton();
        btnEditar.setText("EDITAR");
        Object[] fila = new Object[5];
        fila[0] = producto.getCodigo();
        fila[1] = producto.getNombre();
        fila[2] = producto.getPrecio();
        fila[3] = producto.getStock();
        fila[4] = btnEditar;
        modeloTabla.addRow(fila);
        txtBuscar.requestFocus();

    }

    private void crearListaPreviaProductos(List<Producto> productos) {
        if (!productos.isEmpty()) {
            DefaultListModel<Producto> modelo = new DefaultListModel<>();

            for (Producto producto : productos) {
                modelo.addElement(producto);
            }

            lstPrevia.setModel(modelo);

            lstPrevia.setCellRenderer(new PreviaProductoRenderer());
            //  JList<Producto> lstPreviaProductos=new JList<>(modelo);
            // lstPreviaProductos.setSize(200,200);
            // spnlPrevia.add(lstPreviaProductos);
            pnlPrevia.setVisible(true);
        } else {
            pnlPrevia.setVisible(false);
        }
    }

    private void llenarCombobox() {

        List<Categoria> categorias = negocios.obtenerCategorias();
        Categoria[] arrayCategorias = categorias.toArray(new Categoria[0]);

        cbCategorias.setSelectedItem("Todas");
        cbCategorias.setModel(new DefaultComboBoxModel(arrayCategorias));

    }

    private void cargarTabla() {
        agregaProductos();
    }

    private void agregaProductos() {

        List<Producto> productos = negocios.obtenerProductos();

        negocios.nuevaVenta();

        for (Producto producto : productos) {
            JButton btnEditar = new JButton();
            btnEditar.setText("EDITAR");
            Object[] fila = new Object[5];
            fila[0] = producto.getCodigo();
            fila[1] = producto.getNombre();
            fila[2] = producto.getPrecio();
            fila[3] = producto.getStock();
            fila[4] = btnEditar;
            modeloTabla.addRow(fila);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnAñadirProducto;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVenta;
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JList<Producto> lstPrevia;
    private javax.swing.JPanel pnlPrevia;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
        this.setTitle("Dulcería La Abue | Administrar producto");
        this.setLocationRelativeTo(null);
        tbProductos.getColumn("EDITAR").setCellRenderer(new JTableButtonRenderer());
        modeloTabla = (DefaultTableModel) tbProductos.getModel();
        negocios = getFachadaNegocios();
        cargarTabla();
        llenarCombobox();
        pnlPrevia.setVisible(false);
    }
}
