/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemanenka_presentacion;

import control.INegocios;
import dominio.Categoria;
import dominio.Cliente;
import dominio.Empleado;
import dominio.Producto;
import dominio.Proveedor;
import enums.Rol;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.JTableButtonRenderer;

/**
 *
 * @author dianacastro
 */
public class FrAgregarProducto extends FmBase {

    Empleado empleado;
    INegocios negocios;
    Producto producto;

    /**
     * Creates new form FrAgregarProducto
     */
    public FrAgregarProducto(Empleado empleado, Producto p) {
        initComponents();

        this.empleado = empleado;
        this.producto = p;
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnAdministrador = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        cbCategorias = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnAñadirProducto = new javax.swing.JButton();
        lblProveedor = new javax.swing.JLabel();
        cbProveedores = new javax.swing.JComboBox<>();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(47, 118, 176));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdministrador.setBackground(new java.awt.Color(47, 118, 176));
        btnAdministrador.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/administracion.png"))); // NOI18N
        btnAdministrador.setText("Administrador");
        btnAdministrador.setBorder(null);
        btnAdministrador.setBorderPainted(false);
        btnAdministrador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdministrador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 140, 90));

        btnVenta.setBackground(new java.awt.Color(47, 118, 176));
        btnVenta.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cesta-de-la-compra.png"))); // NOI18N
        btnVenta.setText("Venta");
        btnVenta.setToolTipText("");
        btnVenta.setBorder(null);
        btnVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVenta.setMaximumSize(new java.awt.Dimension(134, 101));
        btnVenta.setMinimumSize(new java.awt.Dimension(134, 101));
        btnVenta.setPreferredSize(new java.awt.Dimension(134, 101));
        btnVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 90));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Productos");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 250, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 620, 110));

        jPanel4.setBackground(new java.awt.Color(47, 111, 159));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("SISTEMA NENKA");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCategoria.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCategoria.setText("Categoria:");
        jPanel1.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 100, 30));

        cbCategorias.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategorias.setBorder(null);
        jPanel1.add(cbCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 210, 30));

        btnCancelar.setBackground(new java.awt.Color(243, 69, 51));
        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 130, 40));

        btnAñadirProducto.setBackground(new java.awt.Color(118, 194, 124));
        btnAñadirProducto.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnAñadirProducto.setText("GUARDAR");
        btnAñadirProducto.setBorder(null);
        btnAñadirProducto.setBorderPainted(false);
        btnAñadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 170, 40));

        lblProveedor.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblProveedor.setText("Proveedor:");
        jPanel1.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 100, 30));

        cbProveedores.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        cbProveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProveedores.setBorder(null);
        jPanel1.add(cbProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 210, 30));

        lblCodigo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCodigo.setText("Código:");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 70, 30));

        txtCodigo.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 210, 30));

        lblStock.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblStock.setText("Stock:");
        jPanel1.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 60, 30));

        lblNombre.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 80, 30));

        lblPrecio.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblPrecio.setText("Precio:");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 70, 30));

        txtStock.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 210, 30));

        txtNombre.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 210, 30));

        txtPrecio.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 770, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministradorActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FmAdministrarProductos fProductos = new FmAdministrarProductos(empleado);
        fProductos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirProductoActionPerformed

        if (validarCamposLlenos()) {

            int opcion = JOptionPane.showConfirmDialog(rootPane,
                    "¿Está seguro que desea guardar los cambios?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION);

            if (opcion == 0) {
                if (producto == null) {
                    negocios.guardarProducto((Categoria) cbCategorias.getSelectedItem(),
                            (Proveedor) cbProveedores.getSelectedItem(), txtNombre.getText(),
                            Float.parseFloat(txtPrecio.getText()), Float.parseFloat(txtStock.getText()),
                            Integer.parseInt(txtCodigo.getText()));

                    FmAdministrarProductos fProductos = new FmAdministrarProductos(empleado);
                    fProductos.setVisible(true);
                    dispose();
                } else {
                    negocios.modificarProducto((Categoria) cbCategorias.getSelectedItem(),
                            (Proveedor) cbProveedores.getSelectedItem(), txtNombre.getText(),
                            Float.parseFloat(txtPrecio.getText()), Float.parseFloat(txtStock.getText()),
                            Integer.parseInt(txtCodigo.getText()));
                    
                    FmAdministrarProductos fProductos = new FmAdministrarProductos(empleado);
                    fProductos.setVisible(true);
                    dispose();
                }

            }

        }
    }//GEN-LAST:event_btnAñadirProductoActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_txtStockKeyTyped

    private void llenarCombobox() {
        List<Categoria> categorias = negocios.obtenerCategorias();
        Categoria[] arrayCategorias = categorias.toArray(new Categoria[0]);

        cbCategorias.setModel(new DefaultComboBoxModel(arrayCategorias));

        List<Proveedor> proveedores = negocios.obtenerProveedores();
        Proveedor[] arrayProveedores = proveedores.toArray(new Proveedor[0]);

        cbProveedores.setModel(new DefaultComboBoxModel(arrayProveedores));
    }

    private void inicializar() {
        negocios = getFachadaNegocios();
        this.setTitle("Dulcería La Abue | Administrar producto");
        this.setLocationRelativeTo(null);
        llenarCombobox();
        if (producto != null) {
            cbCategorias.setSelectedItem(producto.getCategoria());
            cbProveedores.setSelectedItem(producto.getProveedor());
            cbProveedores.setEnabled(false);
            txtNombre.setText(producto.getNombre());
            txtPrecio.setText(Float.toString(producto.getPrecio()));
            txtStock.setText(Double.toString(producto.getStock()));
            txtStock.setEditable(false);
            txtCodigo.setText(producto.getCodigo() + "");
        }

    }

    private boolean validarCamposLlenos() {
        if (txtCodigo.getText().isEmpty() || txtNombre.getText().isEmpty()
                || txtPrecio.getText().isEmpty() || txtStock.getText().isEmpty()) {
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnAñadirProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVenta;
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JComboBox<String> cbProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblStock;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
